### ISSUE TITLE
Instalace - závislosti

### ISSUE THREAD

**Issue by kalab-oto** [OpenGeoLabs/qgis-ndop-downloader#2]
Při instalaci nainstalovat všechny závislosti

**Comment by jachym** [comment]
v branchi https://github.com/OpenGeoLabs/qgis-ndop-downloader/tree/deps jsem zkusil udělat skript, který očuchá prostředí a pokud nějaká knihovna chybí, tkak ji nainstaluje - může být?

ještě to zkusím probrat na nějaky stackexchange: https://gis.stackexchange.com/questions/311726/add-missing-python-packages-to-qgis-plugin

**Comment by kalab-oto** [comment]
nejde snadno vyřešit, nejideálnější je nepoužívat balíčky nainstalované s QGIS (v našem případě asi jenom `pandas` https://github.com/OpenGeoLabs/qgis-ndop-downloader/issues/12). Pokud je takové balíčky nezbytné použít, musím napsat podrobný tutoriál jak je nainstalovat.
