### ISSUE TITLE
Jakým způsobem číst číselníky?

### ISSUE THREAD

**Issue by kalab-oto** [OpenGeoLabs/qgis-ndop-downloader#23]
Číselníky slouží k naplnění komboboxů. Půovdně jsem je stahoval z webu, teď jsem je dal do csv souborů k pluginu do složky [cdb](https://github.com/OpenGeoLabs/qgis-ndop-downloader/tree/master/cdb), abych to urychlil.
Teď, ale nevím jaký je nejlepší (nejsprávnější) způsob jak je nahrát. 

Zatím se nahrávají př každém spuštění, což by mohlo být na hranici pohodlnosti. Je lepší to nastavit aby se to načítalo při spuštění QGIS? To zase bude trochu zpomalovat start QGIS i když se plugin používat nebude. Nebo je jiné řešní?

https://github.com/OpenGeoLabs/qgis-ndop-downloader/blob/2bab6eba13239f12fed98eb605e50997508fd4b9/ndop_downloader.py#L220-L225

**Comment by jachym** [comment]
no, vlastně jsi si odpověděl sám: tak, aby to zdržovalo na tom správnym místě - za mě je to inicializace GUI, ale vážně se to o tolik spomalí? je to pár texťáků, optimalizaci bych řešil, až když se ukáže, že to nějak zásadně zdržuje.

načítat z webu je blbý v tom, že to trvá dýl a taky to nemusí načíst nic (a znemožnit třeba start qgis). je potřeba ale zajistit akutalizační proces že

**Comment by kalab-oto** [comment]
> za mě je to inicializace GUI, 

díky :) hodím to potom tam,teď to zatím to není moc velký problém

> ale vážně se to o tolik spomalí? 

u mě ani ne, ale nevím jak na pmalejších strojích a pokud toho bude potom víc, ale asi to nebude žádná hrůza

> načítat z webu je blbý v tom, že to trvá dýl a taky to nemusí načíst nic (a znemožnit třeba start qgis). je potřeba ale zajistit akutalizační proces že

to bylo dost pomalý, proto jsem to stáhl, zatím jsou jenom 2, v hlavním modulu byla funkce na stahování z netu, tam jsem ji vyměnil na čtení .csv, a funkci jsem upravil a do samostatného skriptu, který potom bude sloužit k automatizaci
